### ISSUE TITLE
Minor: render mermaid to image before publish?

### ISSUE THREAD

**Issue by mmkal** [antfu-collective/importx#9]
### Additional context

npmjs.com doesn't support mermaid rendering, but I and maybe others go to `npmjs.com/package/packagename` when I can't remember who authored it.

GitHub:

<img width="1103" alt="image" src="https://github.com/user-attachments/assets/9590a960-343b-41ba-9ad3-b8ee004f4c54">

npmjs:

<img width="995" alt="image" src="https://github.com/user-attachments/assets/2a58c720-8554-4117-bc6a-eff542a8ca32">

Not sure if there's an easy mermaid->svg/image renderer out there that could be run in `prepack` or something, but if there is it might be worth considering. Or just a link to github for that section - it's a v useful diagram! Feel free to close if that sounds like more effort than it's worth though.

**Comment by antfu** [comment]
I would consider this is something NPM should improve. I think prepacking is too much complexity just for this. To workaround it, I think we could add a link to say, "The follow graph does not renderer? Check it on GitHub". If that sounds good to you, would you like to send a quick PR? Thanks
